services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www
        networks:
            - laravel
        depends_on:
            - db
        working_dir: /var/www
        entrypoint: ["sh", "entrypoint.sh"]

    nginx:
        image: nginx:stable
        container_name: laravel-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:15
        container_name: laravel-postgres
        restart: always
        environment:
            POSTGRES_DB: places
            POSTGRES_USER: root
            POSTGRES_PASSWORD: senha
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

volumes:
    pgdata:

networks:
    laravel:
